application: top-market
version: 4
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on
- admin_redirect: on

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
